### ISSUE TITLE
glDrawFrustrum

### ISSUE THREAD

**Issue by strasdat** [stevenlovegrove/fiducials#1]
Where is "glDrawFrustrum" defined?

main.cpp:128:64: error: ‘glDrawFrustrum’ was not declared in this scope

Cheers,
Hauke

**Comment by stevenlovegrove** [comment]
Ah, that function got renamed to DrawFrustum. I've just updated the samples in fiducials to reflect this, but there might be a few other errors because I'm not building those at the minute (I don't have libCVD building right now). If you're just linking against fiducials, you can safely turn off the samples.

**Comment by stevenlovegrove** [comment]
I installed libcvd and got the samples building again. Let me know if you have any more trouble.

**Comment by strasdat** [comment]
Thanks a lot!!
